### ISSUE TITLE
Add Visual Clue if current edited Intent-Settings match any Intent-Handler

### ISSUE THREAD

**Issue by k3b** [intrications/intent-intercept#12]
While i modify Intent-Settings i want to see if the current settings are valid (no typos, match at least one intent-handler).

Currently i have to scroll down to see if there are matching.

My first attempt to do this is by putting the number of matches in the header - but this looks very ugly. can we somehow  give the user a feedback without the need to scroll down?

**Comment by intrications** [comment]
I have fixed this by disabing/enabling the "Send Edited Intent" button depending on whether the current values are valid or not.

Can you test this and let me know if you see any problems.

**Comment by k3b** [comment]
I have tested it and it works as i expected it.
