### ISSUE TITLE
Hardcoded Strings

### ISSUE THREAD

**Issue by larsgrefer** [intrications/intent-intercept#29]
There are still hardcoded strings in some java files. They should be extracted to string- and plurals-resources in oder to be translated.

Some examples:

https://github.com/intrications/intent-intercept/blob/master/app/src/main/java/uk/co/ashtonbrsc/intentexplode/Explode.java#L625
https://github.com/intrications/intent-intercept/blob/master/app/src/main/java/uk/co/ashtonbrsc/intentexplode/SettingsUtil.java#L45

**Comment by laurencemeynell** [comment]
Hope no one minds, I've started to work through these.  Won't be able to do values-de though.

**Comment by intrications** [comment]
@laurencemeynell 

Feel free to extract more strings. Once your work has been merged, the German translation can easily be done.
