### ISSUE TITLE
Extra values are not copied into clipboard

### ISSUE THREAD

**Issue by techtonik** [intrications/intent-intercept#30]
In version 2.2.1 not all extra values are copied to clipboard. For example, in http://paste.ubuntu.com/12070915/ extra 3 value contains URL to file, which is shown in Intent Intercept interface, but not in the clipboard.

    EXTRA 3:
    Class: android.net.Uri$HierarchicalUri 
    Key: android.intent.extra.STREAM 

The intent is generated by "Graph Paper" Export PDF event.

**Comment by intrications** [comment]
Should be fixed in 2.2.2 just pushed to Google Play Store.

**Comment by techtonik** [comment]
Works like a charm. =)
