### ISSUE TITLE
Catch Various File Chooser Dialogs

### ISSUE THREAD

**Issue by TPS** [intrications/intent-intercept#33]
https://github.com/openintents/notepad has the option to open an arbitrary file, which https://github.com/openintents/filemanager & some other apps catch, but not Intent Intercept.

**Comment by intrications** [comment]
@TPS 

It looks like it might be this intent filter catching it:

```
        <intent-filter>
                <action android:name="org.openintents.action.PICK_FILE" />

                <category android:name="android.intent.category.DEFAULT" />

                <data android:scheme="file" />
                <data android:mimeType="*/*" />
            </intent-filter>
```

https://github.com/openintents/filemanager/blob/master/FileManager/AndroidManifest.xml#L210

This is a non-standard intent action so I'm not sure whether it should be added.

Can you say why are you trying to intercept it?

**Comment by TPS** [comment]
Just because it's an intent that looks to be general enough that non-related products (e.g., OfficeSuite) catch it, but yours doesn't.  Are you sure that's the right intent?  I can't imagine OfficeSuite catching something that specific.…

**Comment by intrications** [comment]
Open Intents was originally meant to define some standards if I remember correctly. So it is very possible that other apps will catch it. I will investigate when I have time.

**Comment by TPS** [comment]
A related 1 that II misses is the File Uploader dialog from Google Docs.  Again, OI File Manager (as well as Gallery & 2 versions of OfficeSuite) catch the intent.  It looks a lot like

![File dialog from http://www.addictivetips.com/android/lesser-known-android-4-4-kitkat-features/](http://cloud.addictivetips.com/wp-content/uploads/2013/11/Android-4.4-KitKat-Lesser-Known-Features-Advanced-File-Picker-02.png)

If II caught it, it would appear in the lower left, alongside Gallery & Photos.

**Comment by TPS** [comment]
@intrications I think https://github.com/intrications/intent-intercept/commit/e2681850fbc27639e64ca2acc1a609a8ee9c58ce solves this.…  Thanks! ☺
