### ISSUE TITLE
Edit value history: remember the last values and allow to pick previous values

### ISSUE THREAD

**Issue by k3b** [intrications/intent-intercept#41]
- In order to test some "ACTION_PICK" implementations 
- i want to add a history funktion to some edit fields 
- so that i can select a previously entered string from a list without the need to retype the text.

This will make intent-intercept independant of first intercepting an intent.

Since i already have implemented this for android before I will add this in the next weeks and supply a merge request when done.

**Comment by intrications** [comment]
Thanks. Sounds like a great idea.

**Comment by k3b** [comment]
implemented with merge request #49
