### ISSUE TITLE
Doesn't intercept firefox "open externally" intents

### ISSUE THREAD

**Issue by wyatt8740** [intrications/intent-intercept#45]
Sorry for the non-technical writing, I'm on my phone and don't want to try to slog through the mozilla codebase from it. I don't think I even have enough storage space. But if you open a direct link to an image, an android logo appears in the URL bar (at least in Aurora), letting you open the image in an external app. However, the photo viewer I want to use is not listed, and since this doesn't catch it I can't figure out which intent it's using.

I can try to gather details later, but I thought I'd report the bug.

**Comment by wyatt8740** [comment]
BTW, this is a nexus 6 on 5.0.1.

**Comment by codebymikey** [comment]
It's not a bug with the app. 

From personal experience with the Firefox app. The android icon only shows up if the app has been compiled to specifically register itself against specific hostnames/urls. e.g. The YouTube/Quora apps.

The closest thing you can do is click the Share button and click the Intent Interceptor icon to inspect.

**Comment by intrications** [comment]
@wyatt8740 

I agree with @codebymikey. If Intent Intercept isn't intercepting the Intent then Firefox is obviously not sharing the image in a standard way.

Probably the only or best way to determine what Firefox is doing is to look at the source.

**Comment by wyatt8740** [comment]
Ah, okay. I have the sourcecode now (on my laptop) and this looks correct, unfortunately. Thanks!
