### ISSUE TITLE
Someome is using intent-intercept to block me out of my phone

### ISSUE THREAD

**Issue by g3tglt** [intrications/intent-intercept#46]
They are using this:  how can i fix this theyve changed my phome num

intent://github.com/intrications/intent-intercept#Intent;scheme=https;category=android.intent.category.BROWSABLE;i.com.google.android.apps.gsa.shared.util.starter.IntentStarter.USE_TRANSITION=1;i.com.google.android.apps.gsa.customtabs.SOURCE=1;i.com.google.android.apps.gsa.customtabs.DEFAULT_ACTION_BUTTON_ID=2;i.com.google.android.apps.gsa.shared.util.starter.IntentStarter.ERROR_TOAST_ID=2131494210;B.com.google.android.apps.gsa.customtabs.EXTRA_CUSTOMTABS_RESOLVED=true;B.com.android.chrome.append_task=true;end    ------------    ACTION: android.intent.action.VIEW    DATA: intent://github.com/intrications/intent-intercept#Intent;scheme=https;category=android.intent.category.BROWSABLE;i.com.google.android.apps.gsa.shared.util.starter.IntentStarter.USE_TRANSITION=1;i.com.google.android.apps.gsa.customtabs.SOURCE=1;i.com.google.android.apps.gsa.customtabs.DEFAULT_ACTION_BUTTON_ID=2;i.com.google.android.apps.gsa.shared.util.starter.IntentStarter.ERROR_TOAST_ID=2131494210;B.com.google.android.apps.gsa.customtabs.EXTRA_CUSTOMTABS_RESOLVED=true;B.com.android.chrome.append_task=true;end    URI: intent://github.com/intrications/intent-intercept#Intent;scheme=https;category=android.intent.category.BROWSABLE;i.com.google.android.apps.gsa.shared.util.starter.IntentStarter.USE_TRANSITION=1;i.com.google.android.apps.gsa.customtabs.SOURCE=1;i.com.google.android.apps.gsa.customtabs.DEFAULT_ACTION_BUTTON_ID=2;i.com.google.android.apps.gsa.shared.util.starter.IntentStarter.ERROR_TOAST_ID=2131494210;B.com.google.android.apps.gsa.customtabs.EXTRA_CUSTOMTABS_RESOLVED=true;B.com.android.chrome.append_task=true;end    FLAGS:    none    EXTRAS:    1 Class: android.net.Uri$HierarchicalUri    Key: android.intent.extra.REFERRER    Value: https://www.google.com    2 Class: android.os.Bundle    Key: com.android.browser.headers 

------------    MATCHING ACTIVITIES:    none

**Comment by intrications** [comment]
@g3tglt Sorry, I do not understand who you think is blocking you out of your phone. Have you tried uninstalling Intent Intercept?
