### ISSUE TITLE
After editing intent no activities match the intent any more

### ISSUE THREAD

**Issue by mucek4** [intrications/intent-intercept#7]
I have installed Intent Interceptor to debug our app's intent. But after changing an intent no activities match any more. As I only changed description (url parameter) and left everything else intact intent should be still matched by all apps.
See attached images.
![2014-07-23 09 50 21](https://cloud.githubusercontent.com/assets/832407/3670013/570d9e8a-123e-11e4-9438-697aad981fab.png)
![2014-07-23 09 50 26](https://cloud.githubusercontent.com/assets/832407/3670014/57102d58-123e-11e4-9b38-8fe18849c982.png)

**Comment by k3b** [comment]
@mucek4  : does the codechange which is available since 28 Dec 2014 solve your problem? can we close this ticket?

**Comment by mucek4** [comment]
The app on Google Play is from 27 May so code is probably not yet released? Right now I have no time to compile it on my own.

**Comment by intrications** [comment]
@mucek4 The app should now be updated on the Google Play Store.

**Comment by mucek4** [comment]
Tested and working.
